### ISSUE TITLE
When exporting targets that are Core Foundation Bundles, properties are set twice

### ISSUE THREAD

**Issue by saxbophone** [mulle-nat/mulle-xcode-to-cmake#10]
This project is a macOS Screensaver: https://github.com/saxbophone/Blank-Mack-Oss-Screensaver/tree/f2487de098cde50e4901b5259989889923dc5f06

If I understand correctly, macOS Screensavers are Core Foundation Bundles (plugin-style).

When exporting such an Xcode project to CMake, `set_target_properties()` is called twice on the Bundle target:

```cmake
if (APPLE)
   set_target_properties( Blank-Mack-Oss-Screensaver PROPERTIES
BUNDLE TRUE
MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/Blank-Mack-Oss-Screensaver-Info.plist.in"
)
endif()

if (APPLE)
   set_target_properties( Blank-Mack-Oss-Screensaver PROPERTIES
MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/Blank-Mack-Oss-Screensaver-Info.plist.in"
)
endif()
```

Note that only the first of these has the property `BUNDLE` set to `TRUE`.

This isn't massively inconvenient and I confess to not know enough about Xcode project internals to know if it is something that can easily be addressed, but it does seem erroneous.

This issue is present in v0.7.1 and at least one other earlier version too.

**Comment by mulle-nat** [comment]
I'll fix this as well. Thanks for the reports.

**Comment by saxbophone** [comment]
No problem.
