### ISSUE TITLE
Failed case with Photoshop SDK

### ISSUE THREAD

**Issue by oryair** [mulle-nat/mulle-xcode-to-cmake#2]
Hey,
I tried to use your product on the default photoshop plugin SDK project.
The files' paths in the output CmakeLists.txt file were incorrect and the plist definition seems to be incorrect

A zip of the project itself (without the full SDK):
[poormanstypetool.xcodeproj.zip](https://github.com/mulle-nat/mulle-xcode-to-cmake/files/2349244/poormanstypetool.xcodeproj.zip)

Thanks!

**Comment by mulle-nat** [comment]
I am not familiar with that project. I am not sure, I'd see offhand what the problem is.
Could you show me some (not all) output that you think is wrong and what the expected output would be.

**Comment by mulle-nat** [comment]
Closed due to lack of input.
