### ISSUE TITLE
Feature request: path modifier

### ISSUE THREAD

**Issue by sakrist** [mulle-nat/mulle-xcode-to-cmake#7]
I love this tool! Thank you for creating it!

Would be excellent addition ability to modify/extended path to files with some argument.

**Comment by mulle-nat** [comment]
Prefixing paths sounds like a good feature. But given current time constraints, it won't happen soon.

**Comment by mulle-nat** [comment]
There is a `--hack-paths` feature. Is this sufficient ? I kinda lost the context on this one.

**Comment by mulle-nat** [comment]
No comment, so I think this is done too.
