### ISSUE TITLE
PROJECT() called before CMAKE_MINIMUM_REQUIRED() in CMake export

### ISSUE THREAD

**Issue by saxbophone** [mulle-nat/mulle-xcode-to-cmake#8]
When exporting this Xcode project I have: https://github.com/saxbophone/Blank-Mack-Oss-Screensaver/tree/f2487de098cde50e4901b5259989889923dc5f06

The generated `CMakeLists.txt` file contains a call to `project()` first, before a call to `cmake_minimum_required()`: https://github.com/saxbophone/Blank-Mack-Oss-Screensaver/blob/ccf8ed83ec45cf7d74b7f4967e6359b3365f02a1/CMakeLists.txt#L1-L7

```cmake
# Generated on 2019-4-16 1:50:56 by version CURRENT_PROJECT_VERSION of mulle-xcode-to-cmake 
# Command line: 
#    mulle-xcode-to-cmake export Blank Mack-Oss Screensaver.xcodeproj/ 

project( Blank Mack-Oss Screensaver) 

cmake_minimum_required (VERSION 3.4) 
```

This can be problematic because if for example, I want to use features of `project()` that only a specific version of CMake includes (like the `VERSION` property), I need to specify the CMake version first.

I think in general, it is conventional to specify the minimum required CMake version before any other commands in a CMake file.

This issue is present in v0.7.1 and at least one other earlier version too.

**Comment by mulle-nat** [comment]
I'll fix this.
