### ISSUE TITLE
CMake project name not quoted when name contains spaces

### ISSUE THREAD

**Issue by saxbophone** [mulle-nat/mulle-xcode-to-cmake#9]
When generating a `CMakeLists.txt` file for an Xcode project which includes space characters in its name: https://github.com/saxbophone/Blank-Mack-Oss-Screensaver/tree/f2487de098cde50e4901b5259989889923dc5f06

The CMake file does not quote the project name that contains spaces: https://github.com/saxbophone/Blank-Mack-Oss-Screensaver/blob/ccf8ed83ec45cf7d74b7f4967e6359b3365f02a1/CMakeLists.txt#L1-L5

```cmake
# Generated on 2019-4-16 1:50:56 by version CURRENT_PROJECT_VERSION of mulle-xcode-to-cmake 
# Command line: 
#    mulle-xcode-to-cmake export Blank Mack-Oss Screensaver.xcodeproj/ 

project( Blank Mack-Oss Screensaver) 
```

This is inconvenient because it leads to a CMake file that will not build, the project name has to be quoted if it contains spaces due to CMake argument-passing conventions.

This issue is present in v0.7.1 and at least one other earlier version too.

**Comment by mulle-nat** [comment]
I'll fix this.
